### PR TITLE
Final milestone: Interactive list

### PR DESCRIPTION
**Pull request by carlylechia**
On this branch, I made the following updates:
 - Added a new JavaScript file and imported it as a module:
 - it contains methods related to the status updates (completed: true / false).
 - Added an event listener to the checkbox (change) and added a line through the checked task.
 - Updated items object's value for completed key upon user actions.
 - Implemented a function for the "Clear all completed" button using the filter() method.
 - Stored the updated array of items in local storage, so the user gets the correct list values after the page reloads.
 - Implemented the function for the refresh button which empties the list.

### CODE REVIEW

**Review by rustam-tolipov — APPROVED** [review]
## Hi @carlylechia 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

Developer-512px-10

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by carlylechia** [comment]
Thank you. I have a problem though, my dashboard is still on `review pending` for this project; please can you do something about that?

**Comment by rustam-tolipov** [comment]
@carlylechia Oh sorry, I forgot about that. It should be working now. **Happy coding ☕**

**Comment by carlylechia** [comment]
Thanks again man

**Pull request merged**
